services:
  postgres:
    image: postgres:15
    container_name: aegis-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aegis_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: aegis-redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: aegis-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: aegis-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data: